### ISSUE TITLE
Sample Enrichment Results don't make sense

### ISSUE THREAD

**Issue by wpoehlm** [SystemsGenetics/KINC.R#1]
I was able to use the help functions in the KINCR package to run the "analyzeNetCat" function.   I thought that the instructions were simple and it seemed to run fine.  However, the p values do not make any sense based on when I spot check the sample compositions of edges with really low p values.  

In the "loadSampleAnnotations" function, it states that the sample order provided as a text file must match the order of sample strings in the KINC output.  

I'm assuming that the sample strings in the KINC(v1.0) output are in the same order as the sample header of the input GEM.  @bentsherman @spficklin can anyone confirm?

**Comment by bentsherman** [comment]
Yes, the order should be the same.

**Comment by wpoehlm** [comment]
After looking at the source code and hand-checking sample-strings, I'm convinced that the P values returned by the analyzeNetCat/analyzeEdgeCat functions correspond to the opposite of the hypothesis that is intended.  If I convert the pval to 1 - pval, the results actually make sense.  

@spficklin We should discuss this in our meeting Thursday, it's probably an easy fix but I'd like someone else to confirm

**Comment by wpoehlm** [comment]
For now, the user must use test = "fishers".  "Binomial" does not work.  I will update the documentation and push a commit
